export const LOAD_SPACE_LIST = 'LOAD_SPACE_LIST';
export const LOAD_SPACE_LIST_BYHOSTID = 'LOAD_SPACE_LIST_BYHOSTID';
export const SET_SPACE_DETAIL = 'SET_SPACE_DETAIL';
export const FILTER_SPACE = 'FILTER_SPACE';
export const SET_SPACE_REGISTER = 'SET_SPACE_REGISTER';
